title: Daniel Soeiro
logo: https://media.licdn.com/dms/image/D4D03AQF-_oRv_0Q1LA/profile-displayphoto-shrink_400_400/0/1668989984246?e=1722470400&v=beta&t=mdVEdv6duAd14gZMMxZwMZlfeH_iU8E7YzQX6RiIE1s
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal
